[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  SECRETS_SCAN_OMIT_KEYS = "JELLY_AI_BASE_URL,JELLY_AI_MODEL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the API redirect - it's breaking Next.js API routes!
# The plugin handles this automatically

